@echo off
rem This file is generated by install.sh — do not edit by hand.
rem install.sh fills in the correct WSL distro, Linux username, and script path.
wsl.exe -d Ubuntu -u YOUR_WSL_USER -- python3 /path/to/printwise/native-host/printwise_host.py
